
spring:
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    #virtual-host:
    port: 5672



person:
  name: 张三
  age: 100
  info: {high: 200CM,weigth: 70KG}